---

# This is close to the standard pipeline, except there’s an extra step in the 
# middle to compile front-end assets.
#
# I tried adding this to the first step, but it usually choked with no actually error message (maybe it hit a secret time limit?)
#
# based on http://robbieminshall.blogspot.de/2015/06/forking-pipelines.html
# docs at https://www.ng.bluemix.net/docs/manageapps/deployingapps.html#sharetextpipelines

stages:
- name: Install Dependencies (npm & bower)
  inputs:
  - type: git
    branch: master
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    build_type: npm
    script: |-
      #!/bin/bash
      npm install
      npm run bower-install
      # note: npm automatically runs the postnatal script in package.json here
      # which installs the bower dependencies
- name: Compile Front-End Assets
  inputs:
  - type: job
    stage: Install Dependencies (npm & bower)
    job: Build
  triggers:
  - type: stage
  jobs:
  - name: gulp build
    type: builder
    build_type: npm
    script: |-
      #!/bin/bash
      npm run gulp-guild
- name: Deploy
  inputs:
  - type: job
    stage: Compile Front-End Assets
    job: Build
  triggers:
  - type: stage
  jobs:
  - name: Deploy to dev
    type: deployer
    target:
      url: ${CF_TARGET_URL}
      organization: ${CF_ORGANIZATION}
      space: ${CF_SPACE}
      application: ${CF_APP}
    script: |-
      #!/bin/bash
      cf push "${CF_APP}"

      # View logs
      #cf logs "${CF_APP}" --recent
